on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: Convert .bu files and release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "coreos/butane"
          latest: true
          fileName: "butane-x86_64-unknown-linux-gnu"
          out-file-path: "bin"

      - run: |
          for FILE in src/*.bu; do
            bin/butane-x86_64-unknown-linux-gnu --pretty --strict $FILE > target/$(echo $FILE | sed 's/.bu$/.ign')
          done
